// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKMIlKs4g6z94xTPeaxdZXEOPkUrZVZ6E',
    appId: '1:403295388918:web:0ad3c8d95321342f8c18d7',
    messagingSenderId: '403295388918',
    projectId: 'absensi-detect',
    authDomain: 'absensi-detect.firebaseapp.com',
    storageBucket: 'absensi-detect.appspot.com',
    measurementId: 'G-MW3VKRF3YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNs5sd2rNljkLaDOGcol-4N4iYVSuKEYU',
    appId: '1:403295388918:android:8444e804147196518c18d7',
    messagingSenderId: '403295388918',
    projectId: 'absensi-detect',
    storageBucket: 'absensi-detect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN5eoLr0qJv2pOCZ0TEjDzTTa4i8ZKTIw',
    appId: '1:403295388918:ios:e4b0b0d3b4ec47948c18d7',
    messagingSenderId: '403295388918',
    projectId: 'absensi-detect',
    storageBucket: 'absensi-detect.appspot.com',
    iosBundleId: 'com.example.absensiDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN5eoLr0qJv2pOCZ0TEjDzTTa4i8ZKTIw',
    appId: '1:403295388918:ios:e4b0b0d3b4ec47948c18d7',
    messagingSenderId: '403295388918',
    projectId: 'absensi-detect',
    storageBucket: 'absensi-detect.appspot.com',
    iosBundleId: 'com.example.absensiDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKMIlKs4g6z94xTPeaxdZXEOPkUrZVZ6E',
    appId: '1:403295388918:web:e6e7fe706621bc5c8c18d7',
    messagingSenderId: '403295388918',
    projectId: 'absensi-detect',
    authDomain: 'absensi-detect.firebaseapp.com',
    storageBucket: 'absensi-detect.appspot.com',
    measurementId: 'G-3LBRLRH8RZ',
  );
}
